//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventorySalesSampleApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InventorySalesDBEntities : DbContext
    {
        public InventorySalesDBEntities()
            : base("name=InventorySalesDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Daily_Inventory_Levels> Daily_Inventory_Levels { get; set; }
        public virtual DbSet<Product_Types> Product_Types { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Products_in_Sales> Products_in_Sales { get; set; }
        public virtual DbSet<Ref_Calendar> Ref_Calendar { get; set; }
        public virtual DbSet<Sale> Sales { get; set; }
        public virtual DbSet<Product_Image> Product_Image { get; set; }
    }
}
