//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventorySalesSampleApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Daily_Inventory_Levels = new HashSet<Daily_Inventory_Levels>();
            this.Products_in_Sales = new HashSet<Products_in_Sales>();
            this.Product_Image = new HashSet<Product_Image>();
        }
    
        public int Id { get; set; }
        public int Product_Type_Code { get; set; }
        public string Product_Name { get; set; }
        public decimal Unit_Price { get; set; }
        public string Product_Description { get; set; }
        public Nullable<int> Reorder_Level { get; set; }
        public Nullable<int> Reorder_Quantity { get; set; }
        public string Other_Details { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Daily_Inventory_Levels> Daily_Inventory_Levels { get; set; }
        public virtual Product_Types Product_Types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Products_in_Sales> Products_in_Sales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Image> Product_Image { get; set; }
    }
}
