//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventorySalesSampleApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Types
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product_Types()
        {
            this.Products = new HashSet<Product>();
            this.Product_Types1 = new HashSet<Product_Types>();
        }
    
        public int Product_Type_Code { get; set; }
        public Nullable<int> Parent_Product_Type_Code { get; set; }
        public string Product_Type_Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_Types> Product_Types1 { get; set; }
        public virtual Product_Types Product_Types2 { get; set; }
    }
}
